config/routes.rb
Rails.application.routes.draw do
  resources :cloud_resources
  resources :compliances
  resources :apps do
    resources :cloud_stacks, shallow: true
  end

  devise_for :users
  resources :owners

  root to: 'homes#index'
end

app/models/cloud_stack.rb
require 'aws-sdk'

class CloudStack < ApplicationRecord
  belongs_to :app

  enum providers: { amazon: 0, google: 1 }
  enum status: { critical_alerts: 0, low_alerts: 1, healthy: 2 }

  has_many :cloud_stack_compliances
  has_many :compliances, through: :cloud_stack_compliances

  accepts_nested_attributes_for :compliances

  def host_platform

  end

  def last_month_cost
    client = Aws::CostExplorer::Client.new
    resp = client.get_cost_and_usage(
      time_period: {
        start: '2021-09-01',
        end: '2021-09-30'
      },
      filter: {
        tags: {
          key: 'APP',
          values: ['fin'],
          match_options: ["EQUALS"]
        }
      },
      granularity: "MONTHLY",
      metrics: ['UsageQuantity']
    )
    resp.results_by_time[0].total
  end

end

app/controllers/cloud_stacks_controller.rb
class CloudStacksController < ApplicationController
  before_action :set_app, only: [:new, :create, :destroy]
  before_action :set_cloud_stack, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json, :xml

  def show
    authorize @cloud_stack, :show?
    respond_with @cloud_stack
  end

  def new
    @cloud_stack = CloudStack.new
    authorize @cloud_stack, :create?
    respond_with @cloud_stack
  end

  def edit
    authorize @cloud_stack, :update?
    respond_with @cloud_stack
  end

  def create
    @cloud_stack = @app.cloud_stacks.new(cloud_stack_params)
    authorize @cloud_stack, :create?
    respond_with @cloud_stack do |format|
      if @cloud_stack.save
        format.html do
          flash[:notice] = I18n.t(:created, model: I18n.t(:cloud_stack, scope: "activerecord.models"))
          redirect_to @app
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    authorize @cloud_stack, :update?
    respond_with @cloud_stack do |format|
      if @cloud_stack.update(cloud_stack_params)
        format.html do
          flash[:notice] = I18n.t(:updated, model: I18n.t(:cloud_stack, scope: "activerecord.models"))
          redirect_to @cloud_stack.app
        end
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    authorize @cloud_stack, :destroy?
    flash[:alert] = I18n.t(:removed, model: I18n.t(:cloud_stack, scope: "activerecord.models")) if @cloud_stack.destroy
    respond_with @app, location: @app
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cloud_stack
    @cloud_stack = CloudStack.find(params[:id])
  end

  def set_app
    @app = App.find(params[:app_id])
  end

  # Only allow a trusted parameter "white list" through.
  def cloud_stack_params
    params.require(:cloud_stack).permit(
      :name,
      :cloud_provider,
      :cloud_provider_id,
      :sla,
      :score,
      :status,
      :product_id,
      :domain_url,
      compliance_ids: []
    )
  end
end

app/views/cloud_stacks/_form.html.erb
<%= simple_form_for([@app, @cloud_stack]) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :cloud_provider, collection: CloudStack.providers.keys, selected: @cloud_stack.cloud_provider %>
    <%= f.input :cloud_provider_id %>
    <%= f.input :sla %>
    <%= f.input :score %>
    <%= f.input :status, collection: CloudStack.statuses.keys %>
    <%= f.input :domain_url %>
    <%= simple_fields_for :compliances do |st| %>
      <% Compliance.order('rule_name').each_with_index do |c, index| %>
        <div class="form-check">
          <%= check_box_tag 'cloud_stack[compliance_ids][]', c.id, @cloud_stack.compliances.map(&:id).include?(c.id), id: "cloud_stack_compliance_id_#{index}", class: 'form-check-input' %>
          <label for="<%= "cloud_stack_compliance_id_#{index}" %>" class="form-check-label"><%= c.rule_name %></label>
        </div>
      <% end %>
    <% end %>
  <hr class="my-4">
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cloud_stacks/edit.html.erb
<%= title t(:editing, model: t(:cloud_stack, scope: "activerecord.models"))  %>

<% content_for :actions do -%>
	<%= link_to t(:back), @cloud_stack.app, class: "btn btn-success" %>
<% end -%>

<%= render 'form' %>

app/views/cloud_stacks/index.html.erb
<h2><%= title t(:cloud_stack, scope: 'activerecord.models').pluralize %></h2>

<% content_for :actions do -%>
  <%= link_to t(:add_model, model: t(:cloud_stack, scope: 'activerecord.models')), new_cloud_stack_path, class: "btn btn-success" %>
<% end -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link @search, :id, t(:id, scope: "activerecord.attributes") %></th>
      <th><%= sort_link @search, :cloud_provider, t(:cloud_provider, scope: "activerecord.attributes.cloud_stack") %></th>
      <th><%= sort_link @search, :cloud_provider_id, t(:cloud_provider_id, scope: "activerecord.attributes.cloud_stack") %></th>
      <th><%= sort_link @search, :sla, t(:sla, scope: "activerecord.attributes.cloud_stack") %></th>
      <th><%= sort_link @search, :score, t(:score, scope: "activerecord.attributes.cloud_stack") %></th>
      <th><%= sort_link @search, :status, t(:status, scope: "activerecord.attributes.cloud_stack") %></th>
      <th><%= sort_link @search, :product, t(:product, scope: "activerecord.attributes.cloud_stack") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @cloud_stacks.each do |cloud_stack| %>
      <tr>
        <td><%= cloud_stack.id %></td>
        <td><%= cloud_stack.cloud_provider %></td>
        <td><%= cloud_stack.cloud_provider_id %></td>
        <td><%= cloud_stack.sla %></td>
        <td><%= cloud_stack.score %></td>
        <td><%= cloud_stack.status %></td>
        <td><%= cloud_stack.product %></td>
        <td>
          <%= link_to cloud_stack, title: t(:visualize) do %>
            <i class="fa fa-eye btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to edit_cloud_stack_path(cloud_stack), title: t(:edit) do %>
            <i class="fa fa-edit btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to cloud_stack, method: :delete, data: { confirm: t(:are_you_sure) }, title: t(:delete) do %>
            <i class="fa fa-trash-o btn btn-danger"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @cloud_stacks %>

app/views/cloud_stacks/new.html.erb
<%= title t(:add_model, model: t(:cloud_stack, scope: 'activerecord.models')) %>

<% content_for :actions do -%>
	<%= link_to t(:back), :back, class: "btn btn-success" %>
<% end -%>

<%= render 'form', app: @app %>

app/views/cloud_stacks/show.html.erb
<%= title t(:cloud_stack, scope: 'activerecord.models').pluralize %>

<% content_for :actions do -%>
	<%= link_to t(:edit), edit_cloud_stack_path(@cloud_stack), class: "btn btn-success" %>
	<%= link_to t(:back), cloud_stacks_path, class: "btn btn-success" %>
<% end -%>

<p>
  <small><%= t(:cloud_provider, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.cloud_provider %></h3>
</p>
<p>
  <small><%= t(:cloud_provider_id, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.cloud_provider_id %></h3>
</p>
<p>
  <small><%= t(:sla, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.sla %></h3>
</p>
<p>
  <small><%= t(:score, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.score %></h3>
</p>
<p>
  <small><%= t(:status, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.status %></h3>
</p>
<p>
  <small><%= t(:product, scope: "activerecord.attributes.cloud_stack") %>:</small>
  <h3><%= @cloud_stack.product %></h3>
</p>