config/routes.rb
Rails.application.routes.draw do
  resources :cloud_resources
  resources :compliances
  resources :apps do
    resources :cloud_stacks, shallow: true
  end

  devise_for :users
  resources :owners

  root to: 'homes#index'
end

app/models/compliance.rb
class Compliance < ApplicationRecord
end

app/controllers/compliances_controller.rb
class CompliancesController < ApplicationController
  before_action :set_compliance, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json, :xml

  def index
    authorize Compliance, :index?
    @search = Compliance.ransack(params[:q])
    @compliances = @search.result.paginate(page: params[:page])
    respond_with @compliances
  end

  def show
    authorize @compliance, :show?
    respond_with @compliance
  end

  def new
    @compliance = Compliance.new
    authorize @compliance, :create?
    respond_with @compliance
  end

  def edit
    authorize @compliance, :update?
    respond_with @compliance
  end

  def create
    @compliance = Compliance.new(compliance_params)
    authorize @compliance, :create?
    respond_with @compliance do |format|
      if @compliance.save
        format.html do
          flash[:notice] = I18n.t(:created, model: I18n.t(:compliance, scope: "activerecord.models"))
          redirect_to @compliance
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    authorize @compliance, :update?
    respond_with @compliance do |format|
      if @compliance.update(compliance_params)
        format.html do
          flash[:notice] = I18n.t(:updated, model: I18n.t(:compliance, scope: "activerecord.models"))
          redirect_to @compliance
        end
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    authorize @compliance, :destroy?
    flash[:alert] = I18n.t(:removed, model: I18n.t(:compliance, scope: "activerecord.models")) if @compliance.destroy
    respond_with @compliance, location: compliances_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_compliance
    @compliance = Compliance.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def compliance_params
    params.require(:compliance).permit(:rule_name, :weight, :deadline, :required_by_law)
  end
end

app/views/compliances/_form.html.erb
<%= simple_form_for(@compliance) do |f| %>
  <%= f.error_notification %>

    <%= f.input :rule_name %>
    <%= f.input :weight %>
    <%= f.input :deadline %>
    <%= f.input :required_by_law %>
  <hr class="my-4">
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/compliances/edit.html.erb
<%= title t(:editing, model: t(:compliance, scope: "activerecord.models"))  %>

<% content_for :actions do -%>
	<%= link_to t(:details), @compliance, class: "btn btn-success" %>
	<%= link_to t(:back), compliances_path, class: "btn btn-success" %>
<% end -%>

<%= render 'form' %>

app/views/compliances/index.html.erb
<h2><%= title t(:compliance, scope: 'activerecord.models').pluralize %></h2>

<% content_for :actions do -%>
  <%= link_to t(:add_model, model: t(:compliance, scope: 'activerecord.models')), new_compliance_path, class: "btn btn-success" %>
<% end -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link @search, :id, t(:id, scope: "activerecord.attributes") %></th>
      <th><%= sort_link @search, :rule_name, t(:rule_name, scope: "activerecord.attributes.compliance") %></th>
      <th><%= sort_link @search, :weight, t(:weight, scope: "activerecord.attributes.compliance") %></th>
      <th><%= sort_link @search, :deadline, t(:deadline, scope: "activerecord.attributes.compliance") %></th>
      <th><%= sort_link @search, :required_by_law, t(:required_by_law, scope: "activerecord.attributes.compliance") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @compliances.each do |compliance| %>
      <tr>
        <td><%= compliance.id %></td>
        <td><%= compliance.rule_name %></td>
        <td><%= compliance.weight %></td>
        <td><%= compliance.deadline %></td>
        <td><%= compliance.required_by_law %></td>
        <td>
          <%= link_to compliance, title: t(:visualize) do %>
            <i class="fa fa-eye btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to edit_compliance_path(compliance), title: t(:edit) do %>
            <i class="fa fa-edit btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to compliance, method: :delete, data: { confirm: t(:are_you_sure) }, title: t(:delete) do %>
            <i class="fa fa-trash-o btn btn-danger"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @compliances %>

app/views/compliances/new.html.erb
<%= title t(:add_model, model: t(:compliance, scope: 'activerecord.models')) %>

<% content_for :actions do -%>
	<%= link_to t(:back), compliances_path, class: "btn btn-success" %>
<% end -%>

<%= render 'form' %>

app/views/compliances/show.html.erb
<%= title t(:compliance, scope: 'activerecord.models').pluralize %>

<% content_for :actions do -%>
	<%= link_to t(:edit), edit_compliance_path(@compliance), class: "btn btn-success" %>
	<%= link_to t(:back), compliances_path, class: "btn btn-success" %>
<% end -%>

<p>
  <small><%= t(:rule_name, scope: "activerecord.attributes.compliance") %>:</small>
  <h3><%= @compliance.rule_name %></h3>
</p>
<p>
  <small><%= t(:weight, scope: "activerecord.attributes.compliance") %>:</small>
  <h3><%= @compliance.weight %></h3>
</p>
<p>
  <small><%= t(:deadline, scope: "activerecord.attributes.compliance") %>:</small>
  <h3><%= @compliance.deadline %></h3>
</p>
<p>
  <small><%= t(:required_by_law, scope: "activerecord.attributes.compliance") %>:</small>
  <h3><%= @compliance.required_by_law %></h3>
</p>