config/routes.rb
Rails.application.routes.draw do
  resources :cloud_resources
  resources :compliances
  resources :apps do
    resources :cloud_stacks, shallow: true
  end

  devise_for :users
  resources :owners

  root to: 'homes#index'
end

app/views/apps/_form.html.erb
<%= simple_form_for(@app) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :is_active %>
    <%= f.input :critical_level, collection: App.critical_levels.keys  %>
    <%= f.input :is_internal %>
    <%= f.input :business_alias %>
    <%= f.input :repository_url %>
    <%= f.input :app_tags %>
    <%= f.association :owner %>
  <hr class="my-4">
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<%= title t(:editing, model: t(:app, scope: "activerecord.models"))  %>

<% content_for :actions do -%>
	<%= link_to t(:details), @app, class: "btn btn-success" %>
	<%= link_to t(:back), apps_path, class: "btn btn-success" %>
<% end -%>

<%= render 'form' %>

app/views/apps/index.html.erb
<h2><%= title t(:app, scope: 'activerecord.models').pluralize %></h2>

<% content_for :actions do -%>
  <%= link_to t(:add_model, model: t(:app, scope: 'activerecord.models')), new_app_path, class: "btn btn-success" %>
<% end -%>

<table class="table table-striped table-light table-bordered">
  <thead>
    <tr class="text-dark">
      <th><%= sort_link @search, :id, t(:id, scope: "activerecord.attributes") %></th>
      <th><%= sort_link @search, :name, t(:name, scope: "activerecord.attributes.app") %></th>
      <th><%= sort_link @search, :is_active, t(:is_active, scope: "activerecord.attributes.app") %></th>
      <th><%= sort_link @search, :critical_level, t(:critical_level, scope: "activerecord.attributes.app") %></th>
      <th><%= sort_link @search, :is_internal, t(:is_internal, scope: "activerecord.attributes.app") %></th>
      <th width="30%"><%= sort_link @search, :owner_name, t(:owner, scope: "activerecord.attributes.app") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @apps.each do |app| %>
      <tr>
        <td><%= app.id %></td>
        <td>
          <b>
            <%= link_to app.name, app %>
          </b>
        </td>
        <td>
          <span class="badge bg-<%= app.is_active ? 'success' : 'danger' %>">
            <%= boolean_label app.is_active %>
          </span>
        </td>
        <td>
          <span class="badge bg-danger bg-opacity-<%= opacity_level(app.critical_level) %>">
            <%= app.critical_level %>
          </span>
        </td>
        <td>
          <span class="badge bg-<%= app.is_internal ? 'success' : 'danger' %>">
            <%= boolean_label app.is_internal %>
          </span>
        </td>
        <td><%= app.owner.try(:name) %></td>
        <td>
          <%= link_to app, title: t(:visualize) do %>
            <i class="fa fa-eye btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to edit_app_path(app), title: t(:edit) do %>
            <i class="fa fa-edit btn btn-default"></i>
          <% end -%>
        </td>
        <td>
          <%= link_to app, method: :delete, data: { confirm: t(:are_you_sure) }, title: t(:delete) do %>
            <i class="fa fa-trash-o btn btn-danger"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @apps %>

app/views/apps/new.html.erb
<%= title t(:add_model, model: t(:app, scope: 'activerecord.models')) %>

<% content_for :actions do -%>
	<%= link_to t(:back), apps_path, class: "btn btn-success" %>
<% end -%>

<%= render 'form' %>

app/views/apps/show.html.erb
<%= title t(:app, scope: 'activerecord.models').pluralize %>

<% content_for :actions do -%>
  <%= link_to t(:edit), edit_app_path(@app), class: "btn btn-success" %>
  <%= link_to t(:back), apps_path, class: "btn btn-success" %>
  <%= link_to t(:add_model, model: t(:'activerecord.models.cloud_stack')), new_app_cloud_stack_path(@app), class: 'btn btn-primary' %>
<% end -%>

<div class="row">
  <div class="col">
    <p>
      <small><%= t(:name, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.name %></h3>
    </p>
    <p>
      <small><%= t(:is_active, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.is_active %></h3>
    </p>
    <p>
      <small><%= t(:critical_level, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.critical_level %></h3>
    </p>
    <p>
      <small><%= t(:is_internal, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.is_internal %></h3>
    </p>
    <p>
      <small><%= t(:business_alias, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.business_alias %></h3>
    </p>
    <p>
      <small><%= t(:repository_url, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.repository_url %></h3>
    </p>
    <p>
      <small><%= t(:app_tags, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.app_tags %></h3>
    </p>
    <p>
      <small><%= t(:owner, scope: "activerecord.attributes.app") %>:</small>
    <h3><%= @app.owner.try(:name) %></h3>
    </p>
  </div>
  <div class="col">
    <% @app.cloud_stacks.each do |cloud_stack| %>
      <div class="card">
        <div class="card-header">
          <%= link_to t(:edit), edit_cloud_stack_path, class: 'btn btn-dark float-end' %>
          <h3>stack: <%= cloud_stack.name %></h3>
        </div>
        <div class="card-body p-0">
          <table class="table table-dark table-hover table-striped">
            <tbody>
            <tr>
              <td width="30%">#ID</td>
              <td><%= cloud_stack.id %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.name') %></td>
              <td><%= cloud_stack.name %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.cloud_provider') %></td>
              <td><%= CloudStack.providers.key(cloud_stack.cloud_provider) %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.cloud_provider_id') %></td>
              <td><%= cloud_stack.cloud_provider_id %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.sla') %></td>
              <td><%= cloud_stack.sla %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.score') %></td>
              <td><%= cloud_stack.score %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.status') %></td>
              <td><%= cloud_stack.status %></td>
            </tr>
            <tr>
              <td><%= t(:'activerecord.attributes.cloud_stack.domain_url') %></td>
              <td><%= cloud_stack.domain_url %></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>