config/routes.rb
Rails.application.routes.draw do
  resources :cloud_resources
  resources :compliances
  resources :apps do
    resources :cloud_stacks, shallow: true
  end

  devise_for :users
  resources :owners

  root to: 'homes#index'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert-container">
    <div class="alert alert-top alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <title>SmartFinOps</title>
  <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag "theme", media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<header>
  <div class="px-3 py-2 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <span class="fs-4">SmartFinOps</span>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li>
            <%= link_to t(:home), root_path, class: 'nav-link px-2 text-secondary' %>
          </li>
          <li>
            <%= link_to t(:'activerecord.models.app').pluralize, apps_path, class: 'nav-link px-2 text-white' %>
          </li>
          <li>
            <%= link_to t(:'activerecord.models.owner').pluralize, owners_path, class: 'nav-link px-2 text-white' %>
          </li>
          <li>
            <%= link_to t(:'activerecord.models.compliance').pluralize, compliances_path, class: 'nav-link px-2 text-white' %>
          </li>
          <li>
            <%= link_to t(:'activerecord.models.cloud_resource').pluralize, cloud_resources_path, class: 'nav-link px-2 text-white' %>
          </li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        <div class="text-end">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light me-2' %>
        </div>
      </div>
    </div>
  </div>
  <div class="px-3 py-2 border-bottom mb-3">
    <div class="container">
      <div class="float-end">
        <%= yield :actions %>
      </div>
      <h4><%= yield :title %></h4>
    </div>
  </div>
</header>
<main>
  <section class="container">
      <%= yield %>
  </section>
</main>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <title>SmartFinOps</title>
  <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag "login", media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body class="login-form text-center">
<main class="form-signin">
    <%= yield %>
</main>
</body>
</html>